"use client"

import { Geist, Geist_Mono } from "next/font/google";

import "./globals.css";
import ReduxProvider from "@/utils/Providers/reduxprovider.js";
import ToasterProvider from "@/utils/Providers/TosterProvider";
import { SessionProvider } from "next-auth/react";
import { ChangeTheme } from "@/utils/Providers/changeThemeProvider";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
      // className={`  ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <SessionProvider>
            <ChangeTheme>
              {children}
            </ChangeTheme>
          </SessionProvider>
        </ReduxProvider>

        <ToasterProvider />

      </body>
    </html>
  );
}
