
import { Geist, Geist_Mono } from "next/font/google";
import { SessionProvider } from "next-auth/react"

import "./globals.css";
import ReduxProvider from "@/utils/Providers/reduxProviders/reduxprovider.js";
import ToasterProvider from "@/utils/Providers/TosterProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" >
      <body
        className={`  ${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </ReduxProvider>

        <ToasterProvider />

      </body>
    </html>
  );
}
